# Generated by Django 4.1.1 on 2022-09-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="auth_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
